# Generated by Django 4.2.4 on 2023-09-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_curso_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'permissions': [('can_view_curso', 'Can view Curso'), ('can_edit_curso', 'Can edit Curso'), ('can_delete_curso', 'Can delete Curso')]},
        ),
    ]
