# Generated by Django 4.2.4 on 2023-09-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_alter_curso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'permissions': [('can_view_curso', 'Can view Curso'), ('can_edit_curso', 'Can edit Curso'), ('can_delete_curso', 'Can delete Curso'), ('can_add_curso', 'Can add Curso')]},
        ),
    ]
